apiVersion: v1
kind: Service
metadata:
  name: transaction-saga-orchestrator
spec:
  type: ClusterIP
  selector:
    app: transaction-saga-orchestrator
  ports:
    - port: 8088
      targetPort: 8088
