apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-saga-orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-saga-orchestrator
  template:
    metadata:
      labels:
        app: account-saga-orchestrator
    spec:
      containers:
        - name: account-saga-orchestrator
          image: account-saga-orchestrator:latest
          imagePullPolicy: IfNotPresent # TODO: ONLY FOR DEV ENVIRONMENT, NOT GOOD FOR PROD
          ports:
            - containerPort: 8087
          env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:postgresql://postgres:5432/account_saga_states_db
                - name: SPRING_DATASOURCE_USERNAME
                  value: test
                - name: SPRING_DATASOURCE_PASSWORD
                  value: test
                - name: SPRINGDOC_SWAGGER-UI_URL
                  value: /v3/api-docs?service=account-saga-orchestrator
                - name: SPRINGDOC_SWAGGER-UI_CONFIG-URL
                  value: /v3/api-docs/swagger-config?service=account-saga-orchestrator